export const Tabel = () => {
  return (
    <div>
      <table>
        <tbody>
          <tr>
            <td>
              <span>Професійний вектор</span>
            </td>
            <td>
              <span>Побут</span>
            </td>
            <td>
              <span>Темперамент</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>Характер</span>
            </td>
            <td>
              <span>Здоров'я</span>
            </td>
            <td>
              <span>Удача</span>
            </td>
            <td>
              <span>Ціль</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>Енергія</span>
            </td>
            <td>
              <span>Логіка</span>
            </td>
            <td>
              <span>Обов'язок</span>
            </td>
            <td>
              <span>Сім'я</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>Інтерес</span>
            </td>
            <td>
              <span>Праця</span>
            </td>
            <td>
              <span>Пам'ять</span>
            </td>
            <td>
              <span>Звички</span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};
